package com.befiring.haduonews.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.befiring.haduonews.bean.News;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEWS".
*/
public class NewsDao extends AbstractDao<News, Long> {

    public static final String TABLENAME = "NEWS";

    /**
     * Properties of entity News.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Date = new Property(2, String.class, "date", false, "DATE");
        public final static Property Thumbnail_pic_s = new Property(3, String.class, "thumbnail_pic_s", false, "THUMBNAIL_PIC_S");
        public final static Property Author_name = new Property(4, String.class, "author_name", false, "AUTHOR_NAME");
        public final static Property Thumbnail_pic_so2 = new Property(5, String.class, "thumbnail_pic_so2", false, "THUMBNAIL_PIC_SO2");
        public final static Property Thumbnail_pic_so3 = new Property(6, String.class, "thumbnail_pic_so3", false, "THUMBNAIL_PIC_SO3");
        public final static Property Url = new Property(7, String.class, "url", false, "URL");
        public final static Property Type = new Property(8, String.class, "type", false, "TYPE");
        public final static Property Realtype = new Property(9, String.class, "realtype", false, "REALTYPE");
    }


    public NewsDao(DaoConfig config) {
        super(config);
    }
    
    public NewsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEWS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"DATE\" TEXT," + // 2: date
                "\"THUMBNAIL_PIC_S\" TEXT," + // 3: thumbnail_pic_s
                "\"AUTHOR_NAME\" TEXT," + // 4: author_name
                "\"THUMBNAIL_PIC_SO2\" TEXT," + // 5: thumbnail_pic_so2
                "\"THUMBNAIL_PIC_SO3\" TEXT," + // 6: thumbnail_pic_so3
                "\"URL\" TEXT," + // 7: url
                "\"TYPE\" TEXT," + // 8: type
                "\"REALTYPE\" TEXT);"); // 9: realtype
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_NEWS_TITLE ON NEWS" +
                " (\"TITLE\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEWS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, News entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        String thumbnail_pic_s = entity.getThumbnail_pic_s();
        if (thumbnail_pic_s != null) {
            stmt.bindString(4, thumbnail_pic_s);
        }
 
        String author_name = entity.getAuthor_name();
        if (author_name != null) {
            stmt.bindString(5, author_name);
        }
 
        String thumbnail_pic_so2 = entity.getThumbnail_pic_so2();
        if (thumbnail_pic_so2 != null) {
            stmt.bindString(6, thumbnail_pic_so2);
        }
 
        String thumbnail_pic_so3 = entity.getThumbnail_pic_so3();
        if (thumbnail_pic_so3 != null) {
            stmt.bindString(7, thumbnail_pic_so3);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(8, url);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(9, type);
        }
 
        String realtype = entity.getRealtype();
        if (realtype != null) {
            stmt.bindString(10, realtype);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, News entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        String thumbnail_pic_s = entity.getThumbnail_pic_s();
        if (thumbnail_pic_s != null) {
            stmt.bindString(4, thumbnail_pic_s);
        }
 
        String author_name = entity.getAuthor_name();
        if (author_name != null) {
            stmt.bindString(5, author_name);
        }
 
        String thumbnail_pic_so2 = entity.getThumbnail_pic_so2();
        if (thumbnail_pic_so2 != null) {
            stmt.bindString(6, thumbnail_pic_so2);
        }
 
        String thumbnail_pic_so3 = entity.getThumbnail_pic_so3();
        if (thumbnail_pic_so3 != null) {
            stmt.bindString(7, thumbnail_pic_so3);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(8, url);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(9, type);
        }
 
        String realtype = entity.getRealtype();
        if (realtype != null) {
            stmt.bindString(10, realtype);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public News readEntity(Cursor cursor, int offset) {
        News entity = new News( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // thumbnail_pic_s
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // author_name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // thumbnail_pic_so2
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // thumbnail_pic_so3
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // url
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // type
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // realtype
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, News entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setThumbnail_pic_s(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAuthor_name(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setThumbnail_pic_so2(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setThumbnail_pic_so3(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUrl(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setType(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setRealtype(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(News entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(News entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(News entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
